const products= [
  //Wigs
  {
    id: 1,
    name: "Straight 24-inch Lace Wig",
    description: "High-quality 100% human hair wig, silky straight 24-inch length, perfect for everyday wear.",
    price: 120.99,
    category: "Wigs",
    subCategory: "Straight Wigs",
    tags: ["featured", "best-seller", "24-inch", "straight"],
    image: "/productsImages/hairProducts/wig1.jpeg",
    stock: 25,
    rating: 4.5 
  },
  {
    id: 2,
    name: "Curly 20-inch Body Wave Wig",
    description: "Luxurious 100% human hair wig with bouncy curls, 20-inch length, soft and easy to style.",
    price: 99.99,
    category: "Wigs",
    subCategory: "Curly Wigs",
    tags: ["new-arrival", "curly", "20-inch"],
    image: "/productsImages/hairProducts/wig2.jpeg",
    stock: 30,
    rating: 4.2
  },
  {
    id: 3,
    name: "13x4 Lace Bob Wig",
    description: "Short bob wig with 13x4 lace, smooth straight hair, natural hairline, easy to maintain.",
    price: 110.00,
    category: "Wigs",
    subCategory: "Bob Wigs",
    tags: ["best-seller", "featured", "short"],
    image: "/productsImages/hairProducts/wig3.jpeg",
    stock: 18,
    rating: 4.6
  },
  {
    id: 4,
    name: "Body Wave 18-inch Wig",
    description: "Soft and natural body wave wig, 18-inch length, perfect for daily wear.",
    price: 105.50,
    category: "Wigs",
    subCategory: "Body Wave Wigs",
    tags: ["curly", "18-inch", "new-arrival"],
    image: "/productsImages/hairProducts/wig4.jpeg",
    stock: 20,
    rating: 4.4,

  },
  {
    id: 5,
    name: "Colored 20-inch Lace Wig",
    description: "Vibrant colored lace wig, 20-inch, smooth and silky, ideal for fashion-forward styles.",
    price: 130.00,
    category: "Wigs",
    subCategory: "Colored Wigs",
    tags: ["featured", "20-inch", "straight"],
    image: "/productsImages/hairProducts/wig5.jpeg",
    stock: 15,
    rating: 4.7
  },
  {
    id: 6,
    name: "Short Curly Bob Wig",
    description: "Cute short bob wig with tight curls, easy to maintain and style for casual or formal occasions.",
    price: 95.00,
    category: "Wigs",
    subCategory: "Bob Wigs",
    tags: ["curly", "new-arrival", "short"],
    image: "/productsImages/hairProducts/wig6.jpeg",
    stock: 22,
    rating: 4.3,
  },
  {
    id: 7,
    name: "360 Lace Body Wave Wig",
    description: "360 lace wig with flowing body waves, natural hairline and full coverage.",
    price: 150.00,
    category: "Wigs",
    subCategory: "360 Lace Wigs",
    tags: ["featured", "best-seller", "body-wave"],
    image: "/productsImages/hairProducts/wig7.jpeg",
    stock: 12,
    rating: 4.8
  },
  {
    id: 8,
    name: "Straight 18-inch Wig",
    description: "Sleek straight wig, 18-inch, lightweight and comfortable for daily use.",
    price: 98.50,
    category: "Wigs",
    subCategory: "Straight Wigs",
    tags: ["straight", "18-inch", "new-arrival"],
    image: "/productsImages/hairProducts/wig8.jpeg",
    stock: 28,
    rating: 4.4
  },
  {
    id: 9,
    name: "Curly 24-inch Lace Wig",
    description: "Long curly lace wig, 24-inch, soft and voluminous, perfect for special events.",
    price: 125.00,
    category: "Wigs",
    subCategory: "Curly Wigs",
    tags: ["curly", "24-inch", "featured"],
    image: "/productsImages/hairProducts/wig9.jpeg",
    stock: 18,
    rating: 4.6
  },
  {
    id: 10,
    name: "Colored Bob Lace Wig",
    description: "Short colored bob wig, stylish and easy to maintain, perfect for modern fashion.",
    price: 105.00,
    category: "Wigs",
    subCategory: "Colored Wigs",
    tags: ["featured", "short", "new-arrival"],
    image: "/productsImages/hairProducts/wig10.jpeg",
    stock: 20,
    rating: 4.5
  },

  // Hair Extensions
  {
    id: 11,
    name: "Straight 24-inch Hair Bundles",
    description: "Premium straight human hair bundles, 24-inch, smooth and silky.",
    price: 89.99,
    category: "Hair Extensions",
    subCategory: "Straight Bundles",
    tags: ["featured", "24-inch", "straight"],
    image: "/productsImages/hairProducts/hx1.jpeg",
    stock: 40,
    rating: 4.5
  },
  {
    id: 12,
    name: "Curly 20-inch Hair Bundles",
    description: "High-quality curly hair bundles, soft and easy to style.",
    price: 85.50,
    category: "Hair Extensions",
    subCategory: "Curly Bundles",
    tags: ["curly", "20-inch", "new-arrival"],
    image: "/productsImages/hairProducts/hx2.jpeg",
    stock: 35,
    rating: 4.4,
  },
  {
    id: 13,
    name: "Body Wave 18-inch Bundles",
    description: "Luxurious body wave bundles, 18-inch, full and soft.",
    price: 80.00,
    category: "Hair Extensions",
    subCategory: "Body Wave Bundles",
    tags: ["body-wave", "18-inch", "best-seller"],
    image: "/productsImages/hairProducts/hx3.jpeg",
    stock: 30,
    rating: 4.6
  },
  {
    id: 14,
    name: "Curly 24-inch Hair Extensions",
    description: "Long curly hair extensions, soft, voluminous and natural-looking.",
    price: 95.00,
    category: "Hair Extensions",
    subCategory: "Curly Bundles",
    tags: ["curly", "24-inch", "featured"],
    image: "/productsImages/hairProducts/hx4.jpeg",
    stock: 25,
    rating: 4.7
  },
  {
    id: 15,
    name: "Straight 20-inch Hair Extensions",
    description: "Sleek straight hair extensions, 20-inch, perfect for layering and styling.",
    price: 90.00,
    category: "Hair Extensions",
    subCategory: "Straight Bundles",
    tags: ["straight", "20-inch", "new-arrival"],
    image: "/productsImages/hairProducts/hx5.jpeg",
    stock: 32,
    rating: 4.5
  },

  // Braids
  {
    id: 16,
    name: "Box Braids 18-inch",
    description: "Premium quality box braids, 18-inch, soft and lightweight.",
    price: 50.00,
    category: "Braids",
    subCategory: "Box Braids",
    tags: ["new-arrival", "18-inch", "braids"],
    image: "/productsImages/hairProducts/braids1.jpeg",
    stock: 40,
    rating: 4.3
  },
  {
    id: 17,
    name: "Cornrows 16-inch",
    description: "Durable and stylish cornrows, perfect for summer and casual looks.",
    price: 45.00,
    category: "Braids",
    subCategory: "Cornrows",
    tags: ["16-inch", "best-seller"],
    image: "/productsImages/hairProducts/braids2.jpeg",
    stock: 30,
    rating: 4.4
  },
  {
    id: 18,
    name: "Twist Braids 20-inch",
    description: "Soft and full twist braids, 20-inch, easy to style and maintain.",
    price: 55.00,
    category: "Braids",
    subCategory: "Twists",
    tags: ["20-inch", "new-arrival", "twist"],
    image: "/productsImages/hairProducts/braids3.jpeg",
    stock: 35,
    rating: 4.5
  },

  // Closures & Frontals
  {
    id: 19,
    name: "4x4 Closure Straight Hair",
    description: "High-quality 4x4 closure, straight human hair, easy to blend.",
    price: 60.00,
    category: "Closures & Frontals",
    subCategory: "4x4 Closures",
    tags: ["featured", "straight", "best-seller"],
    image: "/productsImages/hairProducts/cf1.jpeg",
    stock: 25,
    rating: 4.6
  },
  {
    id: 20,
    name: "13x4 Frontal Body Wave",
    description: "13x4 frontal with body wave texture, soft and natural-looking.",
    price: 70.00,
    category: "Closures & Frontals",
    subCategory: "13x4 Frontals",
    tags: ["featured", "body-wave", "new-arrival"],
    image: "/productsImages/hairProducts/cf2.jpeg",
    stock: 20,
    rating: 4.7
  },
  // Hair Care
  {
    id: 21,
    name: "Moisturizing Shampoo",
    description: "Hydrating shampoo for all hair types, keeps hair soft and healthy.",
    price: 25.00,
    category: "Hair Care",
    subCategory: "Shampoo",
    tags: ["new-arrival", "hair-care"],
    image: "/productsImages/hairProducts/hc1.jpeg",
    stock: 50,
    rating: 4.2
  },
  {
    id: 22,
    name: "Nourishing Conditioner",
    description: "Conditioner for dry and damaged hair, restores shine and softness.",
    price: 27.50,
    category: "Hair Care",
    subCategory: "Conditioner",
    tags: ["hair-care", "featured"],
    image: "/productsImages/hairProducts/hc2.webp",
    stock: 45,
    rating: 4.3
  },
  {
    id: 23,
    name: "Heat Protectant Spray",
    description: "Protects hair from heat damage, keeps hair smooth and healthy.",
    price: 22.00,
    category: "Hair Care",
    subCategory: "Heat Protectant",
    tags: ["featured", "new-arrival"],
    image: "/productsImages/hairProducts/hc3.jpeg",
    stock: 35,
    rating: 4.5
  },
  // Accessories
  {
    id: 24,
    name: "Premium Hair Brush",
    description: "Soft bristle hair brush, gentle on scalp and prevents breakage.",
    price: 18.00,
    category: "Accessories",
    subCategory: "Brushes",
    tags: ["featured", "hair-care"],
    image: "/productsImages/hairProducts/acc1.jpeg",
    stock: 60,
    rating: 4.4
  },
  {
    id: 25,
    name: "Hair Clips Set",
    description: "Set of 12 colorful hair clips, perfect for styling and sectioning hair.",
    price: 12.00,
    category: "Accessories",
    subCategory: "Clips",
    tags: ["new-arrival", "accessory"],
    image: "/productsImages/hairProducts/acc2.jpeg",
    stock: 80,
    rating: 4.5
  },
  //Wigs
  {
    id: 26,
    name: "Long Curly 22-inch Wig",
    description: "Voluminous curly wig, 22-inch, soft and natural, perfect for party looks.",
    price: 125.00,
    category: "Wigs",
    subCategory: "Curly Wigs",
    tags: ["curly", "22-inch", "featured"],
    image: "/productsImages/hairProducts/wig11.webp",
    stock: 20,
    rating: 4.6
  },
  {
    id: 27,
    name: "Straight 20-inch Bob Wig",
    description: "Smooth straight bob wig, 20-inch, easy to style and maintain.",
    price: 110.00,
    category: "Wigs",
    subCategory: "Bob Wigs",
    tags: ["straight", "20-inch", "new-arrival"],
    image: "/productsImages/hairProducts/wig12.jpeg",
    stock: 18,
    rating: 4.5
  },
  {
    id: 28,
    name: "Colored 18-inch Bob Wig",
    description: "Short colored bob wig, vibrant and stylish, perfect for fashion trends.",
    price: 105.00,
    category: "Wigs",
    subCategory: "Colored Wigs",
    tags: ["colored", "18-inch", "new-arrival"],
    image: "/productsImages/hairProducts/wig13.jpeg",
    stock: 15,
    rating: 4.4
  },
  {
    id: 29,
    name: "Body Wave 24-inch Wig",
    description: "Long body wave wig, 24-inch, luxurious and soft, ideal for elegant styles.",
    price: 135.00,
    category: "Wigs",
    subCategory: "Body Wave Wigs",
    tags: ["body-wave", "24-inch", "featured"],
    image: "/productsImages/hairProducts/wig14.jpeg",
    stock: 12,
    rating: 4.7
  },
  {
    id: 30,
    name: "360 Lace Curly Wig",
    description: "360 lace wig with tight curls, full coverage, natural look and soft texture.",
    price: 155.00,
    category: "Wigs",
    subCategory: "360 Lace Wigs",
    tags: ["curly", "featured", "best-seller"],
    image: "/productsImages/hairProducts/wig15.jpeg",
    stock: 10,
    rating: 4.8
  },

  // Hair Extensions
  {
    id: 31,
    name: "Straight 18-inch Hair Bundles",
    description: "High-quality straight bundles, 18-inch, silky and natural.",
    price: 82.00,
    category: "Hair Extensions",
    subCategory: "Straight Bundles",
    tags: ["straight", "18-inch", "new-arrival"],
    image: "/productsImages/hairProducts/hx6.jpeg",
    stock: 30,
    rating: 4.4
  },
  {
    id: 32,
    name: "Curly 22-inch Hair Bundles",
    description: "Long curly hair bundles, 22-inch, soft, natural, and full-bodied.",
    price: 95.00,
    category: "Hair Extensions",
    subCategory: "Curly Bundles",
    tags: ["curly", "22-inch", "featured"],
    image: "/productsImages/hairProducts/hx7.jpeg",
    stock: 28,
    rating: 4.5
  },
  {
    id: 33,
    name: "Body Wave 20-inch Bundles",
    description: "Luxurious body wave bundles, 20-inch, shiny and full-bodied.",
    price: 88.00,
    category: "Hair Extensions",
    subCategory: "Body Wave Bundles",
    tags: ["body-wave", "20-inch", "best-seller"],
    image: "/productsImages/hairProducts/hx8.jpeg",
    stock: 25,
    rating: 4.6
  },
  {
    id: 34,
    name: "Straight 24-inch Hair Extensions",
    description: "Sleek straight hair extensions, 24-inch, perfect for layering.",
    price: 92.00,
    category: "Hair Extensions",
    subCategory: "Straight Bundles",
    tags: ["straight", "24-inch", "featured"],
    image: "/productsImages/hairProducts/hx9.jpeg",
    stock: 22,
    rating: 4.7
  },
  {
    id: 35,
    name: "Curly 18-inch Hair Extensions",
    description: "Short curly extensions, 18-inch, soft and easy to blend.",
    price: 85.00,
    category: "Hair Extensions",
    subCategory: "Curly Bundles",
    tags: ["curly", "18-inch", "new-arrival"],
    image: "/productsImages/hairProducts/hx10.jpeg",
    stock: 30,
    rating: 4.5
  },

  // Braids
  {
    id: 36,
    name: "Box Braids 20-inch",
    description: "Soft, lightweight box braids, 20-inch, perfect for summer looks.",
    price: 52.00,
    category: "Braids",
    subCategory: "Box Braids",
    tags: ["20-inch", "featured"],
    image: "/productsImages/hairProducts/braids4.jpeg",
    stock: 35,
    rating: 4.4
  },
  {
    id: 37,
    name: "Cornrows 18-inch",
    description: "Durable cornrows, 18-inch, stylish and low-maintenance.",
    price: 48.00,
    category: "Braids",
    subCategory: "Cornrows",
    tags: ["18-inch", "best-seller"],
    image: "/productsImages/hairProducts/braids5.jpeg",
    stock: 28,
    rating: 4.5
  },
  {
    id: 38,
    name: "Twist Braids 22-inch",
    description: "Soft twist braids, 22-inch, easy to maintain and versatile.",
    price: 58.00,
    category: "Braids",
    subCategory: "Twists",
    tags: ["22-inch", "new-arrival"],
    image: "/productsImages/hairProducts/braids6.jpeg",
    stock: 30,
    rating: 4.6
  },

  // Closures & Frontals
  {
    id: 39,
    name: "4x4 Closure Body Wave",
    description: "High-quality 4x4 closure with soft body wave texture.",
    price: 62.00,
    category: "Closures & Frontals",
    subCategory: "4x4 Closures",
    tags: ["body-wave", "featured"],
    image: "/productsImages/hairProducts/cf3.jpeg",
    stock: 22,
    rating: 4.6
  },
  {
    id: 40,
    name: "13x4 Frontal Curly",
    description: "13x4 frontal with tight curls, natural hairline and volume.",
    price: 72.00,
    category: "Closures & Frontals",
    subCategory: "13x4 Frontals",
    tags: ["curly", "featured"],
    image: "/productsImages/hairProducts/cf4.jpeg",
    stock: 18,
    rating: 4.7
  },

  // Hair Care
  {
    id: 41,
    name: "Repair Hair Mask",
    description: "Deep conditioning mask for damaged hair, restores softness and shine.",
    price: 30.00,
    category: "Hair Care",
    subCategory: "Mask",
    tags: ["new-arrival", "hair-care"],
    image: "/productsImages/hairProducts/hc4.webp",
    stock: 40,
    rating: 4.4
  },                         
  {
    id: 42,
    name: "Leave-in Conditioner",
    description: "Hydrating leave-in conditioner, perfect for frizz control and shine.",
    price: 28.00,
    category: "Hair Care",
    subCategory: "Conditioner",
    tags: ["featured", "hair-care"],
    image: "/productsImages/hairProducts/hc5.jpeg",
    stock: 35,
    rating: 4.5
  },
  {
    id: 43,
    name: "Hair Growth Oil",
    description: "Nourishing oil to stimulate hair growth and strengthen strands.",
    price: 35.00,
    category: "Hair Care",
    subCategory: "Oils",
    tags: ["featured", "new-arrival"],
    image: "/productsImages/hairProducts/hc6.webp",
    stock: 30,
    rating: 4.6
  },

  // Accessories
  {
    id: 44,
    name: "Detangling Brush",
    description: "Soft detangling brush, gentle on scalp and hair.",
    price: 20.00,
    category: "Accessories",
    subCategory: "Brushes",
    tags: ["hair-care", "featured"],
    image: "/productsImages/hairProducts/acc3.jpeg",
    stock: 50,
    rating: 4.5
  },
  {
    id: 45,
    name: "Sectioning Clips",
    description: "Set of 10 sectioning clips, perfect for styling and braiding.",
    price: 14.00,
    category: "Accessories",
    subCategory: "Clips",
    tags: ["new-arrival", "accessory"],
    image: "/productsImages/hairProducts/acc4.jpeg",
    stock: 60,
    rating: 4.4
  },
  {
    id: 46,
    name: "Combs Set",
    description: "Set of professional combs for styling, sectioning, and detangling.",
    price: 18.00,
    category: "Accessories",
    subCategory: "Combs",
    tags: ["featured", "hair-care"],
    image: "/productsImages/hairProducts/acc5.webp",
    stock: 55,
    rating: 4.5
  },
  {
    id: 47,
    name: "Silk Hair Scarf",
    description: "Premium silk hair scarf, protects hair while sleeping and adds style.",
    price: 15.00,
    category: "Accessories",
    subCategory: "Scarves",
    tags: ["new-arrival", "accessory"],
    image: "/productsImages/hairProducts/acc6.jpeg",
    stock: 40,
    rating: 4.4
  },
  {
    id: 48,
    name: "Elastic Hair Bands",
    description: "Durable and flexible hair bands for all hair types.",
    price: 10.00,
    category: "Accessories",
    subCategory: "Bands",
    tags: ["hair-care", "featured"],
    image: "/productsImages/hairProducts/acc7.jpeg",
    stock: 70,
    rating: 4.5
  },
  {
    id: 49,
    name: "Hair Pins Set",
    description: "Set of 20 hair pins for styling, securing, and creating hairstyles.",
    price: 12.00,
    category: "Accessories",
    subCategory: "Pins",
    tags: ["new-arrival", "accessory"],
    image: "/productsImages/hairProducts/acc8.jpeg",
    stock: 65,
    rating: 4.4
  },
  {
    id: 50,
    name: "Wide-tooth Comb",
    description: "Gentle wide-tooth comb for detangling wet or curly hair.",
    price: 15.00,
    category: "Accessories",
    subCategory: "Combs",
    tags: ["hair-care", "featured"],
    image: "/productsImages/hairProducts/acc9.jpeg",
    stock: 60,
    rating: 4.5
  },
];

export default products

